default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: estimates_development

test:
  <<: *default
  database: estimates_test

production:
  <<: *default
  database: estimates_production
  username: fdh_web_app
  password: <%= ENV["DEV_ESTIMATION_DATABASE_PASSWORD"] %>
